#!/bin/sh
#src/js/appnet-util.js \
"/usr/local/bin/node" "node_modules/jshint/bin/hint" --config=lint-config.js \
src/js/appnet-api.js \
src/js/appnet-note.js \
src/js/appnet.js \
src/js/ChatForm.js \
src/js/ChatHistory.js \
src/js/editRoomModal.js \
src/js/lobby.js \
src/js/netclient-api.js \
src/js/netclient.js \
src/js/netserver.js \
src/js/PatterEmbed.js \
src/js/room.js \
src/js/RoomFeed.js \
src/js/roomInfo.js \
src/js/roomMenu.js \
src/js/UserFields.js \
src/js/UserList.js \
src/js/util.js \
&& \
cd src/js && \
"/usr/local/bin/node" ../../r.js -o build.js && \
cd ../.. && \
pwd && \
chmod -R og+r * && \
cp src/require-jquery.js out/js
